// Generates src/app/tokens.css from design/tokens.json (the Deen Squad design system).
// Run with `npm run tokens` after updating design/tokens.json. The output is committed.
import { readFileSync, writeFileSync } from "node:fs";

const tokens = JSON.parse(readFileSync(new URL("../design/tokens.json", import.meta.url), "utf8"));
const [light, dark] = tokens.color.themes.map((t) => t.id);

// The app names radii by the product they belong to, so `rounded-app` reads better than `rounded-l`
// and does not collide with Tailwind's logical `rounded-s-*` utilities.
const radiusAlias = { "radius-s": "dash", "radius-m": "web", "radius-l": "app", "radius-pill": "pill" };

const lines = [];
const out = (s = "") => lines.push(s);

out("/* GENERATED by scripts/build-tokens.mjs from design/tokens.json. Do not edit by hand. */");
out();
out(":root {");
for (const t of tokens.color.tokens) out(`  --${t.name}: ${t.value[light]};`);
for (const t of tokens.shadow.tokens) out(`  --${t.name}: ${t.value[light]};`);
for (const t of tokens.spacing.tokens) out(`  --${t.name}: ${t.value};`);
for (const t of tokens.radius.tokens) out(`  --${t.name}: ${t.value};`);
for (const [key, stack] of Object.entries(tokens.type.families)) out(`  --font-${key}: ${stack};`);
out("  color-scheme: light;");
out("}");
out();
out("@media (prefers-color-scheme: dark) {");
out("  :root {");
for (const t of tokens.color.tokens) if (t.value[dark] !== t.value[light]) out(`    --${t.name}: ${t.value[dark]};`);
for (const t of tokens.shadow.tokens) if (t.value[dark] !== t.value[light]) out(`    --${t.name}: ${t.value[dark]};`);
out("    color-scheme: dark;");
out("  }");
out("}");
out();
out("@theme inline {");
for (const t of tokens.color.tokens) out(`  --color-${t.name}: var(--${t.name});`);
for (const t of tokens.shadow.tokens) out(`  --shadow-${t.name}: var(--${t.name});`);
for (const t of tokens.radius.tokens) out(`  --radius-${radiusAlias[t.name] ?? t.name}: var(--${t.name});`);
for (const key of Object.keys(tokens.type.families)) out(`  --font-${key}: var(--font-${key});`);
for (const group of tokens.type.groups) {
  for (const s of group.styles) {
    out(`  --text-${s.name}: ${s.fontSize};`);
    const lh = typeof s.lineHeight === "number" ? String(s.lineHeight) : s.lineHeight;
    if (lh) out(`  --text-${s.name}--line-height: ${lh};`);
    if (s.letterSpacing) out(`  --text-${s.name}--letter-spacing: ${s.letterSpacing};`);
    if (s.fontWeight) out(`  --text-${s.name}--font-weight: ${s.fontWeight};`);
  }
}
out("}");
out();

writeFileSync(new URL("../src/app/tokens.css", import.meta.url), lines.join("\n"));
console.log(`tokens.css written: ${tokens.color.tokens.length} colours, ${tokens.type.groups.reduce((n, g) => n + g.styles.length, 0)} text styles`);
