// Builds public/offline-pass.js, the script of the offline attendance QR page (public/offline-pass.html),
// from src/offline/pass-page.ts with the app's own QR library (qrcode, MIT). Run `npm run offline` after
// changing either, or src/lib/pass/cache.ts, and bump VERSION in public/sw.js so phones fetch the new copy.
// src/offline/build.test.ts fails while the committed file is out of date.
// Uses rolldown, which comes with Vite (Vitest), so nothing extra is installed.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { rolldown } from "rolldown";

export const OFFLINE_OUT = fileURLToPath(new URL("../public/offline-pass.js", import.meta.url));

const BANNER = `/* Deen Squad offline attendance QR page. Generated by scripts/build-offline.mjs from src/offline/pass-page.ts: don't edit.
 * Includes qrcode (https://github.com/soldair/node-qrcode, MIT, Copyright (c) 2012 Ryan Day) and dijkstrajs (MIT). */`;

/** The built script, as text. */
export async function buildOffline() {
  const bundle = await rolldown({
    input: fileURLToPath(new URL("../src/offline/pass-page.ts", import.meta.url)),
    platform: "browser",
    logLevel: "silent",
  });
  try {
    const { output } = await bundle.generate({ format: "iife", minify: true, postBanner: BANNER, sourcemap: false });
    return output[0].code;
  } finally {
    await bundle.close();
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(OFFLINE_OUT, await buildOffline());
  console.log(`Wrote ${OFFLINE_OUT}`);
}
